services:

  schoolbox-external-db-circuit-breaker:
    image: jimdavis66/schoolbox-external-db-circuit-breaker:latest
    container_name: schoolbox-external-db-circuit-breaker
    restart: always
    network_mode: host
    env_file: .env

# Local Dev Environment
  # schoolbox-external-db-circuit-breaker:
  #   build: .
  #   container_name: schoolbox-external-db-circuit-breaker
  #   volumes:
  #     - ./app:/app
  #   env_file: .env
  #   depends_on:
  #     - mysql
  
  # mysql:
  #   build: ./mysql/
  #   container_name: mysql
  #   environment:
  #     MYSQL_DATABASE: 'db'
  #     MYSQL_USER: 'user'
  #     MYSQL_PASSWORD: 'password'
  #     MYSQL_ROOT_PASSWORD: 'secret'
  #   ports:
  #     - '3306:3306'


